server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Giousa/springcloud-config.git #GitHub上面的git仓库名字
#          uri: git@github.com:Giousa/springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
#          username: giousa
#          passphrase: ssss
          search-paths:
#            - springcloud-config
            - config
      ####读取分支
      label: main
  #rabbitmq相关配置
  rabbitmq:
    host: 139.224.46.106
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

#rabbitmq相关配置,暴露bus刷新配置的端点
#bus-refresh 是和里面默认配置相关
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'


