server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 139.224.46.106:8848 #配置Nacos地址
        server-addr: 139.224.46.106:1111 #nginx+nacos+mysql

management:
  endpoints:
    web:
      exposure:
        include: '*'


